
version: 2

jobs:
  build:
    branches:
      only:
        - master
        - beta

    docker:
      - image: circleci/node:8.4.0

    working_directory: ~/zeo

    steps:
      - checkout

      - run: npm install

      - run: npm run build

      - store_artifacts:
          path: ~/zeo/windows-release.zip
          destination: windows-release.zip
